### PR TITLE
bug fix: SmartCharts stuck in loading screen in binary-static

### PR DESCRIPTION
**Pull request by brucebinary**
To replicate, set the URL to end with `#/` (e.g. `http://localhost:8080/index.html#/`)

additional bug fix: shared URL should link to charts.binary.com

### CODE REVIEW

**Comment by brucebinary** [comment]
@aminroosta how will the implementation work if it is used by library users? Note that binary-static developers use `*.binary.sx` as well.

**Comment by aminroosta** [comment]
@brucebinary  in that case let's make it a config option 

`<SmartCharts  shareEndpoint={"https://charts.binary.com"}  ... />`

binary-static will pass "charts.binary.com" but applications will pass their own href
For example if i want to make it work on my .sx domain all i need to do is

`<SmartCharts shareEndpoint={window.location.href.split('?')[0]} ... />`

**Comment by aminroosta** [comment]
make the `shareEndpoint` optional, defaulting to `https://charts.binary.com`

**Comment by brucebinary** [comment]
@aminroosta ah that works better. But maybe call it `shareOrigin` instead?

**Comment by aminroosta** [comment]
Yea, sure ... sounds good to me

**Comment by brucebinary** [comment]
@aminroosta I just added the prop.

**Comment by aminroosta** [comment]
@brucebinary Let's get this merged.

**Pull request merged**
